### PR TITLE
Simple logic improvements + standards

### PR DESCRIPTION
**Pull request by emptyshells**
**Additions**

- JSHint for linting
- Changelog
- Unit test skeleton

**Changes**

- Logic in main class: is it assumed that `context` always exists (i.e. is non-null)?

### CODE REVIEW

**Comment by Mania36** [comment]
Note that `package-lock.json` is adding lots of lines to the commit log. :wink:

**Comment by manixate** [comment]
Thanks for the PR. A couple of points:

1. It does not work with Insomnia because of the use of named import. Request Hooks need function as input so you have to update `index.js` file as well. I don't see any benefits in using named import considering the file is supposed to only export 1 hook.
2. Context will always be present as that is the input from Insomnia and it will be valid.
3. The tests are not testing anything there. It would be great if the tests were testing the functionality of the plugin i.e if the values are read properly from environment variables and adding proper header values.
4. We should keep the formatting consistent with existing styles as that is what we use throughout our projects i.e use of spaces. Adding a linter is a good idea but I would prefer using ESLint instead of JSHint because we can use a predefined standard e.g plugin and the errors are more verbose in ESLint.
5. Small changes should not update the minor project version because there is no functionality change. Instead, the version should have been 1.0.5.

**Comment by puppynapper** [comment]
I'll update the PR as according to your suggestions:

1. Revert named import.
2. Remove null check on context.
3. Provide AT LEAST one unit test that does something.  I agree with you that having unit tests that don't do anything are misleading, and produce quite the opposite outcome of the desired result when it comes to testing.  I just wanted to get some implementation of a framework out there.
4. Replace JSHint with ESLint.
5. Update semver to patch bump instead of a minor version bump.
6. Use `const` instead of `let` where applicable.

**Comment by puppynapper** [comment]
I updated all of the above except for (3).  Other work is taking priority right now.  If not having a thorough unit test is blocking this PR from getting merged then I will come back to it when I have time.

**Comment by emptyshells** [comment]
Sorry for the lack of communication.  I've been on call for production support this week.  I'm looking to get these resolved by Friday.  Thank you for your patience!

**Pull request closed without merging**
